targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: uk
          fallback_strategy: base_locale
          input_directory: lib/core/localization/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/core/localization
          output_file_name: translations.g.dart
          lazy: false
          locale_handling: true
          flutter_integration: true
